#**DNA**

seq1

In [1]:
seq1 = input("first seq : ") # seq 1 입력
lseq1 = list(seq1)

first seq : AAAAA


seq2

In [2]:
seq2 = input("second seq : ") # seq 2 입력
lseq2 = list(seq2)

second seq : TTTTT


match score, mismatch score, gap score

In [3]:
gap_score = input("gap score : ") # gap score 입력
match_score = input("match score : ") # match score 입력
mismatch_score = input("mismatch score : ") # mismatch score 입력

gap score : -2
match score : -1
mismatch score : 1


#**Protein**

In [4]:
seq1 = input("first seq : ") # seq 1 입력
lseq1 = list(seq1)

first seq : HEAGAWGHEE


In [5]:
seq2 = input("second seq : ") # seq 2 입력
lseq2 = list(seq2)

second seq : PAWHEAE


In [6]:
gap_opening = input("gap opening penalty : ") # gap opening penalty
gap_extension_penalty = input("gap extension penalty : ") #gap extension penalty

gap opening penalty : -10
gap extension penalty : -10


In [7]:
print(len(seq1))
print(len(seq2))

10
7


#Matrix 가져오기

In [8]:
import os

In [9]:
file_path = '/content/drive/MyDrive/Colab Notebooks/의생명정보학/score_matrix'

###BLOSUM62 불러오기

In [10]:
with open(os.path.join(file_path,'BLOSUM62.txt')) as f:
    lines = f.read().splitlines()

In [11]:
BLOSUM62 = []
for i in range(len(lines)):
  BLOSUM62.append(lines[i].split())

for i in range(len(lines)):
  del BLOSUM62[i][-1]

del BLOSUM62[-1]

BLOSUM62[0].insert(0,' ')

In [12]:
for i in range(len(lines)-1):
  print(BLOSUM62[i])

[' ', 'A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V', 'B', 'J', 'Z', 'X']
['A', '4', '-1', '-2', '-2', '0', '-1', '-1', '0', '-2', '-1', '-1', '-1', '-1', '-2', '-1', '1', '0', '-3', '-2', '0', '-2', '-1', '-1', '-1']
['R', '-1', '5', '0', '-2', '-3', '1', '0', '-2', '0', '-3', '-2', '2', '-1', '-3', '-2', '-1', '-1', '-3', '-2', '-3', '-1', '-2', '0', '-1']
['N', '-2', '0', '6', '1', '-3', '0', '0', '0', '1', '-3', '-3', '0', '-2', '-3', '-2', '1', '0', '-4', '-2', '-3', '4', '-3', '0', '-1']
['D', '-2', '-2', '1', '6', '-3', '0', '2', '-1', '-1', '-3', '-4', '-1', '-3', '-3', '-1', '0', '-1', '-4', '-3', '-3', '4', '-3', '1', '-1']
['C', '0', '-3', '-3', '-3', '9', '-3', '-4', '-3', '-3', '-1', '-1', '-3', '-1', '-2', '-3', '-1', '-1', '-2', '-2', '-1', '-3', '-1', '-3', '-1']
['Q', '-1', '1', '0', '0', '-3', '5', '2', '-2', '0', '-3', '-2', '1', '0', '-3', '-1', '0', '-1', '-2', '-1', '-2', '0', '-2', '4', '-1']
['E', '-1', '0', '0

###PAM250 불러오기

In [13]:
with open(os.path.join(file_path,'PAM250.txt')) as f:
    lines = f.read().splitlines()

In [14]:
PAM250 = []
for i in range(len(lines)):
  PAM250.append(lines[i].split())

for i in range(len(lines)):
  del PAM250[i][-1]

del PAM250[-1]

PAM250[0].insert(0,' ')

In [15]:
for i in range(len(lines)-1):
  print(PAM250[i])

[' ', 'A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V', 'B', 'J', 'Z', 'X']
['A', '2', '-2', '0', '0', '-2', '0', '0', '1', '-1', '-1', '-2', '-1', '-1', '-3', '1', '1', '1', '-6', '-3', '0', '0', '-1', '0', '-1']
['R', '-2', '6', '0', '-1', '-4', '1', '-1', '-3', '2', '-2', '-3', '3', '0', '-4', '0', '0', '-1', '2', '-4', '-2', '-1', '-3', '0', '-1']
['N', '0', '0', '2', '2', '-4', '1', '1', '0', '2', '-2', '-3', '1', '-2', '-3', '0', '1', '0', '-4', '-2', '-2', '2', '-3', '1', '-1']
['D', '0', '-1', '2', '4', '-5', '2', '3', '1', '1', '-2', '-4', '0', '-3', '-6', '-1', '0', '0', '-7', '-4', '-2', '3', '-3', '3', '-1']
['C', '-2', '-4', '-4', '-5', '12', '-5', '-5', '-3', '-3', '-2', '-6', '-5', '-5', '-4', '-3', '0', '-2', '-8', '0', '-2', '-4', '-5', '-5', '-1']
['Q', '0', '1', '1', '2', '-5', '4', '2', '-1', '3', '-2', '-2', '1', '-1', '-5', '0', '-1', '-1', '-5', '-4', '-2', '1', '-2', '3', '-1']
['E', '0', '-1', '1', '3', '-5', '2

###PAM30 불러오기

In [16]:
with open(os.path.join(file_path,'PAM30.txt')) as f:
    lines = f.read().splitlines()

In [17]:
PAM30 = []
for i in range(len(lines)):
  PAM30.append(lines[i].split())

for i in range(len(lines)):
  del PAM30[i][-1]

del PAM30[-1]

PAM30[0].insert(0,' ')

In [18]:
for i in range(len(lines)-1):
  print(PAM30[i])

[' ', 'A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V', 'B', 'J', 'Z', 'X']
['A', '6', '-7', '-4', '-3', '-6', '-4', '-2', '-2', '-7', '-5', '-6', '-7', '-5', '-8', '-2', '0', '-1', '-13', '-8', '-2', '-3', '-6', '-3', '-1']
['R', '-7', '8', '-6', '-10', '-8', '-2', '-9', '-9', '-2', '-5', '-8', '0', '-4', '-9', '-4', '-3', '-6', '-2', '-10', '-8', '-7', '-7', '-4', '-1']
['N', '-4', '-6', '8', '2', '-11', '-3', '-2', '-3', '0', '-5', '-7', '-1', '-9', '-9', '-6', '0', '-2', '-8', '-4', '-8', '6', '-6', '-3', '-1']
['D', '-3', '-10', '2', '8', '-14', '-2', '2', '-3', '-4', '-7', '-12', '-4', '-11', '-15', '-8', '-4', '-5', '-15', '-11', '-8', '6', '-10', '1', '-1']
['C', '-6', '-8', '-11', '-14', '10', '-14', '-14', '-9', '-7', '-6', '-15', '-14', '-13', '-13', '-8', '-3', '-8', '-15', '-4', '-6', '-12', '-9', '-14', '-1']
['Q', '-4', '-2', '-3', '-2', '-14', '8', '1', '-7', '1', '-8', '-5', '-3', '-4', '-13', '-3', '-5', '-5', '-13', '

###PAM70불러오기

In [19]:
with open(os.path.join(file_path,'PAM70.txt')) as f:
    lines = f.read().splitlines()

In [20]:
PAM70 = []
for i in range(len(lines)):
  PAM70.append(lines[i].split())

for i in range(len(lines)):
  del PAM70[i][-1]

del PAM70[-1]

PAM70[0].insert(0,' ')

###BLOSUM45

In [21]:
with open(os.path.join(file_path,'BLOSUM45.txt')) as f:
    lines = f.read().splitlines()

In [22]:
BLOSUM45 = []
for i in range(len(lines)):
  BLOSUM45.append(lines[i].split())

for i in range(len(lines)):
  del BLOSUM45[i][-1]

del BLOSUM45[-1]

BLOSUM45[0].insert(0,' ')

###BLOSUM50

In [23]:
with open(os.path.join(file_path,'BLOSUM50.txt')) as f:
    lines = f.read().splitlines()

In [24]:
BLOSUM50 = []
for i in range(len(lines)):
  BLOSUM50.append(lines[i].split())

for i in range(len(lines)):
  del BLOSUM50[i][-1]

del BLOSUM50[-1]

BLOSUM50[0].insert(0,' ')

###BLOSUM80

In [25]:
with open(os.path.join(file_path,'BLOSUM80.txt')) as f:
    lines = f.read().splitlines()

In [26]:
BLOSUM80 = []
for i in range(len(lines)):
  BLOSUM80.append(lines[i].split())

for i in range(len(lines)):
  del BLOSUM80[i][-1]

del BLOSUM80[-1]

BLOSUM80[0].insert(0,' ')

###BLOSUM90

In [27]:
with open(os.path.join(file_path,'BLOSUM90.txt')) as f:
    lines = f.read().splitlines()

In [28]:
BLOSUM90 = []
for i in range(len(lines)):
  BLOSUM90.append(lines[i].split())

for i in range(len(lines)):
  del BLOSUM90[i][-1]

del BLOSUM90[-1]

BLOSUM90[0].insert(0,' ')

In [29]:
for i in range(len(lines)-1):
  print(BLOSUM90[i])

[' ', 'A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V', 'B', 'J', 'Z', 'X']
['A', '5', '-2', '-2', '-3', '-1', '-1', '-1', '0', '-2', '-2', '-2', '-1', '-2', '-3', '-1', '1', '0', '-4', '-3', '-1', '-2', '-2', '-1', '-1']
['R', '-2', '6', '-1', '-3', '-5', '1', '-1', '-3', '0', '-4', '-3', '2', '-2', '-4', '-3', '-1', '-2', '-4', '-3', '-3', '-2', '-3', '0', '-1']
['N', '-2', '-1', '7', '1', '-4', '0', '-1', '-1', '0', '-4', '-4', '0', '-3', '-4', '-3', '0', '0', '-5', '-3', '-4', '5', '-4', '-1', '-1']
['D', '-3', '-3', '1', '7', '-5', '-1', '1', '-2', '-2', '-5', '-5', '-1', '-4', '-5', '-3', '-1', '-2', '-6', '-4', '-5', '5', '-5', '1', '-1']
['C', '-1', '-5', '-4', '-5', '9', '-4', '-6', '-4', '-5', '-2', '-2', '-4', '-2', '-3', '-4', '-2', '-2', '-4', '-4', '-2', '-4', '-2', '-5', '-1']
['Q', '-1', '1', '0', '-1', '-4', '7', '2', '-3', '1', '-4', '-3', '1', '0', '-4', '-2', '-1', '-1', '-3', '-3', '-3', '-1', '-3', '5', '-1']
['E',

#**Score Matrix 생성 후 계산하기**

In [30]:
# 0으로 score matrix 초기화
score_matrix1 = [['0'] * (len(seq1)+2) for _ in range(len(seq2)+2) ]

for i in range(2,len(seq1)+2,1):
  score_matrix1[0][i] = lseq1[i-2]

for i in range(2,len(lseq2)+2,1):
  score_matrix1[i][0] = lseq2[i-2]

# gap score 추가 
for i in range(1,len(seq1)+2,1):
  if i == 1:
    score_matrix1[1][i] = '0'
  else:
    a = int(score_matrix1[1][i-1]) + int(gap_opening)
    score_matrix1[1][i] = str(a)

for i in range(1,len(seq2)+2,1):
  if i == 1:
    score_matrix1[i][1] = '0'
  else:
    a = int(score_matrix1[i-1][1]) + int(gap_opening)
    score_matrix1[i][1] = str(a)  

In [31]:
score_matrix2 = [['0'] * (len(seq1)+2) for _ in range(len(seq2)+2) ]

for i in range(2,len(seq1)+2,1):
  score_matrix2[0][i] = lseq1[i-2]

for i in range(2,len(lseq2)+2,1):
  score_matrix2[i][0] = lseq2[i-2]

# gap score 추가 
for i in range(1,len(seq1)+2,1):
  if i == 1:
    score_matrix2[1][i] = '0'
  else:
    a = int(score_matrix2[1][i-1]) + int(gap_opening)
    score_matrix2[1][i] = str(a)

for i in range(1,len(seq2)+2,1):
  if i == 1:
    score_matrix2[i][1] = '0'
  else:
    a = int(score_matrix2[i-1][1]) + int(gap_opening)
    score_matrix2[i][1] = str(a)    

In [32]:
score_matrix3 = [['0'] * (len(seq1)+2) for _ in range(len(seq2)+2) ]

for i in range(2,len(seq1)+2,1):
  score_matrix3[0][i] = lseq1[i-2]

for i in range(2,len(lseq2)+2,1):
  score_matrix3[i][0] = lseq2[i-2]

# gap score 추가 
for i in range(1,len(seq1)+2,1):
  if i == 1:
    score_matrix3[1][i] = '0'
  else:
    a = int(score_matrix3[1][i-1]) + int(gap_opening)
    score_matrix3[1][i] = str(a)

for i in range(1,len(seq2)+2,1):
  if i == 1:
    score_matrix3[i][1] = '0'
  else:
    a = int(score_matrix3[i-1][1]) + int(gap_opening)
    score_matrix3[i][1] = str(a)    

In [33]:
score_matrix4 = [['0'] * (len(seq1)+2) for _ in range(len(seq2)+2) ]

for i in range(2,len(seq1)+2,1):
  score_matrix4[0][i] = lseq1[i-2]

for i in range(2,len(lseq2)+2,1):
  score_matrix4[i][0] = lseq2[i-2]

# gap score 추가 
for i in range(1,len(seq1)+2,1):
  if i == 1:
    score_matrix4[1][i] = '0'
  else:
    a = int(score_matrix4[1][i-1]) + int(gap_opening)
    score_matrix4[1][i] = str(a)

for i in range(1,len(seq2)+2,1):
  if i == 1:
    score_matrix4[i][1] = '0'
  else:
    a = int(score_matrix4[i-1][1]) + int(gap_opening)
    score_matrix4[i][1] = str(a)  

In [34]:
score_matrix5 = [['0'] * (len(seq1)+2) for _ in range(len(seq2)+2) ]

for i in range(2,len(seq1)+2,1):
  score_matrix5[0][i] = lseq1[i-2]

for i in range(2,len(lseq2)+2,1):
  score_matrix5[i][0] = lseq2[i-2]

# gap score 추가 
for i in range(1,len(seq1)+2,1):
  if i == 1:
    score_matrix5[1][i] = '0'
  else:
    a = int(score_matrix5[1][i-1]) + int(gap_opening)
    score_matrix5[1][i] = str(a)

for i in range(1,len(seq2)+2,1):
  if i == 1:
    score_matrix5[i][1] = '0'
  else:
    a = int(score_matrix5[i-1][1]) + int(gap_opening)
    score_matrix5[i][1] = str(a)  

In [35]:
score_matrix6 = [['0'] * (len(seq1)+2) for _ in range(len(seq2)+2) ]

for i in range(2,len(seq1)+2,1):
  score_matrix6[0][i] = lseq1[i-2]

for i in range(2,len(lseq2)+2,1):
  score_matrix6[i][0] = lseq2[i-2]

# gap score 추가 
for i in range(1,len(seq1)+2,1):
  if i == 1:
    score_matrix6[1][i] = '0'
  else:
    a = int(score_matrix6[1][i-1]) + int(gap_opening)
    score_matrix6[1][i] = str(a)

for i in range(1,len(seq2)+2,1):
  if i == 1:
    score_matrix6[i][1] = '0'
  else:
    a = int(score_matrix6[i-1][1]) + int(gap_opening)
    score_matrix6[i][1] = str(a)  

In [36]:
score_matrix7 = [['0'] * (len(seq1)+2) for _ in range(len(seq2)+2) ]

for i in range(2,len(seq1)+2,1):
  score_matrix7[0][i] = lseq1[i-2]

for i in range(2,len(lseq2)+2,1):
  score_matrix7[i][0] = lseq2[i-2]

# gap score 추가 
for i in range(1,len(seq1)+2,1):
  if i == 1:
    score_matrix7[1][i] = '0'
  else:
    a = int(score_matrix7[1][i-1]) + int(gap_opening)
    score_matrix7[1][i] = str(a)

for i in range(1,len(seq2)+2,1):
  if i == 1:
    score_matrix7[i][1] = '0'
  else:
    a = int(score_matrix7[i-1][1]) + int(gap_opening)
    score_matrix7[i][1] = str(a)  

In [37]:
score_matrix8 = [['0'] * (len(seq1)+2) for _ in range(len(seq2)+2) ]

for i in range(2,len(seq1)+2,1):
  score_matrix8[0][i] = lseq1[i-2]

for i in range(2,len(lseq2)+2,1):
  score_matrix8[i][0] = lseq2[i-2]

# gap score 추가 
for i in range(1,len(seq1)+2,1):
  if i == 1:
    score_matrix8[1][i] = '0'
  else:
    a = int(score_matrix8[1][i-1]) + int(gap_opening)
    score_matrix8[1][i] = str(a)

for i in range(1,len(seq2)+2,1):
  if i == 1:
    score_matrix8[i][1] = '0'
  else:
    a = int(score_matrix8[i-1][1]) + int(gap_opening)
    score_matrix8[i][1] = str(a)  

In [38]:
score_matrix8[8]

['E', '-70', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

In [39]:
for i in range(len(seq2)+2):
  print(score_matrix8[i])

['0', '0', 'H', 'E', 'A', 'G', 'A', 'W', 'G', 'H', 'E', 'E']
['0', '0', '-10', '-20', '-30', '-40', '-50', '-60', '-70', '-80', '-90', '-100']
['P', '-10', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
['A', '-20', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
['W', '-30', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
['H', '-40', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
['E', '-50', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
['A', '-60', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
['E', '-70', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']


In [40]:
#for i in range(1,len(seq1)+2,1):
#  if i == 1:
#    score_matrix1[1][i] = '0'
#  else:
#    a = int(score_matrix1[1][i-1]) + int(gap_opening)
#    score_matrix1[1][i] = str(a)

#for i in range(1,len(seq2)+2,1):
#  if i == 1:
#    score_matrix1[i][1] = '0'
#  else:
#    a = int(score_matrix1[i-1][1]) + int(gap_opening)
#    score_matrix1[i][1] = str(a)

In [41]:
#for i in range(len(seq2)+2):
#  print(score_matrix1[i])

In [42]:
import numpy as np

In [43]:
direction_matrix1 = np.zeros((3,len(seq2)+2,len(seq1)+2))
direction_matrix2 = np.zeros((3,len(seq2)+2,len(seq1)+2))
direction_matrix3 = np.zeros((3,len(seq2)+2,len(seq1)+2))
direction_matrix4 = np.zeros((3,len(seq2)+2,len(seq1)+2))
direction_matrix5 = np.zeros((3,len(seq2)+2,len(seq1)+2))
direction_matrix6 = np.zeros((3,len(seq2)+2,len(seq1)+2))
direction_matrix7 = np.zeros((3,len(seq2)+2,len(seq1)+2))
direction_matrix8 = np.zeros((3,len(seq2)+2,len(seq1)+2))

###Score Matrix 불러오기

In [44]:
def matrix_score1(amino1,amino2):
  a = 0
  b = 0
  c = -100000
  for i in range(1,len(BLOSUM62),1):
    if BLOSUM62[0][i] == amino1:
      a = i
  for i in range(1,len(BLOSUM62),1):
    if BLOSUM62[i][0] == amino2:
      b = i
  
  c = BLOSUM62[a][b]

  return c

In [45]:
def matrix_score2(amino1,amino2):
  a = 0
  b = 0
  c = -100000
  for i in range(1,len(PAM250),1):
    if PAM250[0][i] == amino1:
      a = i
  for i in range(1,len(PAM250),1):
    if PAM250[i][0] == amino2:
      b = i
  
  c = PAM250[a][b]

  return c

In [46]:
def matrix_score3(amino1,amino2):
  a = 0
  b = 0
  c = -100000
  for i in range(1,len(PAM30),1):
    if PAM30[0][i] == amino1:
      a = i
  for i in range(1,len(PAM30),1):
    if PAM30[i][0] == amino2:
      b = i
  
  c = PAM30[a][b]

  return c

In [47]:
def matrix_score4(amino1,amino2):
  a = 0
  b = 0
  c = -100000
  for i in range(1,len(PAM70),1):
    if PAM70[0][i] == amino1:
      a = i
  for i in range(1,len(PAM70),1):
    if PAM70[i][0] == amino2:
      b = i
  
  c = PAM70[a][b]

  return c

In [48]:
def matrix_score5(amino1,amino2):
  a = 0
  b = 0
  c = -100000
  for i in range(1,len(BLOSUM45),1):
    if BLOSUM45[0][i] == amino1:
      a = i
  for i in range(1,len(BLOSUM45),1):
    if BLOSUM45[i][0] == amino2:
      b = i
  
  c = BLOSUM45[a][b]

  return c

In [49]:
def matrix_score6(amino1,amino2):
  a = 0
  b = 0
  c = -100000
  for i in range(1,len(BLOSUM50),1):
    if BLOSUM50[0][i] == amino1:
      a = i
  for i in range(1,len(BLOSUM50),1):
    if BLOSUM50[i][0] == amino2:
      b = i
  
  c = BLOSUM50[a][b]

  return c

In [50]:
def matrix_score7(amino1,amino2):
  a = 0
  b = 0
  c = -100000
  for i in range(1,len(BLOSUM80),1):
    if BLOSUM80[0][i] == amino1:
      a = i
  for i in range(1,len(BLOSUM80),1):
    if BLOSUM80[i][0] == amino2:
      b = i
  
  c = BLOSUM80[a][b]

  return c

In [51]:
def matrix_score8(amino1,amino2):
  a = 0
  b = 0
  c = -100000
  for i in range(1,len(BLOSUM90),1):
    if BLOSUM90[0][i] == amino1:
      a = i
  for i in range(1,len(BLOSUM90),1):
    if BLOSUM90[i][0] == amino2:
      b = i
  
  c = BLOSUM90[a][b]

  return c

###Score Matrix 점수내기

In [52]:
for i in range(2,len(seq2)+2,1):
  for j in range(2,len(seq1)+2,1):
        
    s1 = int(score_matrix1[i-1][j-1]) + int(matrix_score1(score_matrix1[i][0],score_matrix1[0][j]))
    s2 = int(score_matrix1[i-1][j]) + int(gap_opening)
    s3 = int(score_matrix1[i][j-1]) + int(gap_opening)
    
    score_matrix1[i][j] = str(max(s1,s2,s3))

    if str(max(s1,s2,s3)) == str(s1):
      #대각선 방향
      direction_matrix1[0][i][j] = 1
    if str(max(s1,s2,s3)) == str(s2):
      direction_matrix1[1][i][j] = 1
    if str(max(s1,s2,s3)) == str(s3):
      direction_matrix1[2][i][j] = 1

In [53]:
for i in range(2,len(seq2)+2,1):
  for j in range(2,len(seq1)+2,1):
        
    s1 = int(score_matrix2[i-1][j-1]) + int(matrix_score2(score_matrix2[i][0],score_matrix2[0][j]))
    s2 = int(score_matrix2[i-1][j]) + int(gap_opening)
    s3 = int(score_matrix2[i][j-1]) + int(gap_opening)
    
    score_matrix2[i][j] = str(max(s1,s2,s3))

    if str(max(s1,s2,s3)) == str(s1):
      #대각선 방향
      direction_matrix2[0][i][j] = 1
    if str(max(s1,s2,s3)) == str(s2):
      direction_matrix2[1][i][j] = 1
    if str(max(s1,s2,s3)) == str(s3):
      direction_matrix2[2][i][j] = 1

In [54]:
for i in range(2,len(seq2)+2,1):
  for j in range(2,len(seq1)+2,1):
        
    s1 = int(score_matrix3[i-1][j-1]) + int(matrix_score3(score_matrix3[i][0],score_matrix3[0][j]))
    s2 = int(score_matrix3[i-1][j]) + int(gap_opening)
    s3 = int(score_matrix3[i][j-1]) + int(gap_opening)
    
    score_matrix3[i][j] = str(max(s1,s2,s3))

    if str(max(s1,s2,s3)) == str(s1):
      #대각선 방향
      direction_matrix3[0][i][j] = 1
    if str(max(s1,s2,s3)) == str(s2):
      direction_matrix3[1][i][j] = 1
    if str(max(s1,s2,s3)) == str(s3):
      direction_matrix3[2][i][j] = 1

In [55]:
for i in range(2,len(seq2)+2,1):
  for j in range(2,len(seq1)+2,1):
        
    s1 = int(score_matrix4[i-1][j-1]) + int(matrix_score4(score_matrix4[i][0],score_matrix4[0][j]))
    s2 = int(score_matrix4[i-1][j]) + int(gap_opening)
    s3 = int(score_matrix4[i][j-1]) + int(gap_opening)
    
    score_matrix4[i][j] = str(max(s1,s2,s3))

    if str(max(s1,s2,s3)) == str(s1):
      #대각선 방향
      direction_matrix4[0][i][j] = 1
    if str(max(s1,s2,s3)) == str(s2):
      direction_matrix4[1][i][j] = 1
    if str(max(s1,s2,s3)) == str(s3):
      direction_matrix4[2][i][j] = 1

In [56]:
for i in range(2,len(seq2)+2,1):
  for j in range(2,len(seq1)+2,1):
        
    s1 = int(score_matrix5[i-1][j-1]) + int(matrix_score5(score_matrix5[i][0],score_matrix5[0][j]))
    s2 = int(score_matrix5[i-1][j]) + int(gap_opening)
    s3 = int(score_matrix5[i][j-1]) + int(gap_opening)
    
    score_matrix5[i][j] = str(max(s1,s2,s3))

    if str(max(s1,s2,s3)) == str(s1):
      #대각선 방향
      direction_matrix5[0][i][j] = 1
    if str(max(s1,s2,s3)) == str(s2):
      direction_matrix5[1][i][j] = 1
    if str(max(s1,s2,s3)) == str(s3):
      direction_matrix5[2][i][j] = 1

In [57]:
for i in range(2,len(seq2)+2,1):
  for j in range(2,len(seq1)+2,1):
        
    s1 = int(score_matrix6[i-1][j-1]) + int(matrix_score6(score_matrix6[i][0],score_matrix6[0][j]))
    s2 = int(score_matrix6[i-1][j]) + int(gap_opening)
    s3 = int(score_matrix6[i][j-1]) + int(gap_opening)
    
    score_matrix6[i][j] = str(max(s1,s2,s3))

    if str(max(s1,s2,s3)) == str(s1):
      #대각선 방향
      direction_matrix6[0][i][j] = 1
    if str(max(s1,s2,s3)) == str(s2):
      direction_matrix6[1][i][j] = 1
    if str(max(s1,s2,s3)) == str(s3):
      direction_matrix6[2][i][j] = 1

In [58]:
for i in range(2,len(seq2)+2,1):
  for j in range(2,len(seq1)+2,1):
        
    s1 = int(score_matrix7[i-1][j-1]) + int(matrix_score7(score_matrix7[i][0],score_matrix7[0][j]))
    s2 = int(score_matrix7[i-1][j]) + int(gap_opening)
    s3 = int(score_matrix7[i][j-1]) + int(gap_opening)
    
    score_matrix7[i][j] = str(max(s1,s2,s3))

    if str(max(s1,s2,s3)) == str(s1):
      #대각선 방향
      direction_matrix7[0][i][j] = 1
    if str(max(s1,s2,s3)) == str(s2):
      direction_matrix7[1][i][j] = 1
    if str(max(s1,s2,s3)) == str(s3):
      direction_matrix7[2][i][j] = 1

In [59]:
for i in range(2,len(seq2)+2,1):
  for j in range(2,len(seq1)+2,1):
        
    s1 = int(score_matrix8[i-1][j-1]) + int(matrix_score8(score_matrix8[i][0],score_matrix8[0][j]))
    s2 = int(score_matrix8[i-1][j]) + int(gap_opening)
    s3 = int(score_matrix8[i][j-1]) + int(gap_opening)
    
    score_matrix8[i][j] = str(max(s1,s2,s3))

    if str(max(s1,s2,s3)) == str(s1):
      #대각선 방향
      direction_matrix8[0][i][j] = 1
    if str(max(s1,s2,s3)) == str(s2):
      direction_matrix8[1][i][j] = 1
    if str(max(s1,s2,s3)) == str(s3):
      direction_matrix8[2][i][j] = 1

In [60]:
for i in range(len(seq2)+2):
  print(score_matrix2[i])

['0', '0', 'H', 'E', 'A', 'G', 'A', 'W', 'G', 'H', 'E', 'E']
['0', '0', '-10', '-20', '-30', '-40', '-50', '-60', '-70', '-80', '-90', '-100']
['P', '-10', '0', '-10', '-19', '-29', '-39', '-49', '-59', '-69', '-79', '-89']
['A', '-20', '-10', '0', '-8', '-18', '-27', '-37', '-47', '-57', '-67', '-77']
['W', '-30', '-20', '-10', '-6', '-15', '-24', '-10', '-20', '-30', '-40', '-50']
['H', '-40', '-24', '-19', '-11', '-8', '-16', '-20', '-12', '-14', '-24', '-34']
['E', '-50', '-34', '-20', '-19', '-11', '-8', '-18', '-20', '-11', '-10', '-20']
['A', '-60', '-44', '-30', '-18', '-18', '-9', '-14', '-17', '-21', '-11', '-10']
['E', '-70', '-54', '-40', '-28', '-18', '-18', '-16', '-14', '-16', '-17', '-7']


In [61]:
print(direction_matrix8)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
  [0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0.]
  [0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1.]
  [0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

##Alignment sequence 계산

###BLOSUM62 결과

In [62]:
start_seq1_BLOSUM62 = len(seq1)+1
start_seq2_BLOSUM62 = len(seq2)+1
rev_seq1_BLOSUM62 = []
rev_seq2_BLOSUM62 = []

for i in range(len(seq2)+1,1,-1):
  for j in range(len(seq1)+1,1,-1):
    #print("바깥 i 는 ",i)
    #print("바깥 j 는 ",j)

    if i == start_seq2_BLOSUM62 and j == start_seq1_BLOSUM62:

      #print("안쪽 i 는 ",i)
      #print("안쪽 j 는 ",j)
      #print("start_seq2 는 ",start_seq2)
      #print("start_seq1 은 ",start_seq1)
      
      if direction_matrix1[0][i][j] == 1:
        sc1 = int(score_matrix1[i-1][j-1])
      else:
        sc1 = -1000000
      
      if direction_matrix1[1][i][j] == 1:
        sc2 = int(score_matrix1[i-1][j])
      else:
        sc2 = -1000000
      
      if direction_matrix1[2][i][j] == 1:
        sc3 = int(score_matrix1[i][j-1])
      else:
        sc3 = -1000000

      if str(max(sc1,sc2,sc3)) == str(sc1):
        rev_seq1_BLOSUM62.append(score_matrix1[0][j])
        rev_seq2_BLOSUM62.append(score_matrix1[i][0])
        start_seq1_BLOSUM62 = start_seq1_BLOSUM62 - 1
        start_seq2_BLOSUM62 = start_seq2_BLOSUM62 - 1

      elif str(max(sc1,sc2,sc3)) == str(sc2):
        rev_seq1_BLOSUM62.append('-')
        rev_seq2_BLOSUM62.append(score_matrix1[i][0])
        start_seq2_BLOSUM62 = start_seq2_BLOSUM62 - 1
    
      else:
        rev_seq1_BLOSUM62.append(score_matrix1[0][j])
        rev_seq2_BLOSUM62.append('-')
        start_seq1_BLOSUM62 = start_seq1_BLOSUM62 - 1

      if start_seq2_BLOSUM62==1:
        while start_seq1_BLOSUM62 != 1:
          rev_seq1_BLOSUM62.append(score_matrix1[0][start_seq1_BLOSUM62])
          rev_seq2_BLOSUM62.append('-')
          start_seq1_BLOSUM62 = start_seq1_BLOSUM62 - 1

      elif start_seq1_BLOSUM62==1:
        while start_seq2_BLOSUM62 != 1:
          rev_seq1_BLOSUM62.append('-')
          rev_seq2_BLOSUM62.append(score_matrix1[start_seq2_BLOSUM62][0])
          start_seq2_BLOSUM62 = start_seq2_BLOSUM62 - 1
      
      #print(rev_seq1)
      #print(rev_seq2)
  

In [63]:
rev_seq1_BLOSUM62.reverse()
rev_seq2_BLOSUM62.reverse()
best_seq1_BLOSUM62 = "".join(rev_seq1_BLOSUM62)
best_seq2_BLOSUM62 = "".join(rev_seq2_BLOSUM62)
print("---Protein Global Alignment---")
print("best seq1 : ",best_seq1_BLOSUM62)
print("best seq2 : ",best_seq2_BLOSUM62)

---Protein Global Alignment---
best seq1 :  HEAGAWGHEE
best seq2 :  -PA--WHEAE


In [64]:
print(rev_seq1_BLOSUM62)

['H', 'E', 'A', 'G', 'A', 'W', 'G', 'H', 'E', 'E']


In [65]:
print(rev_seq2_BLOSUM62)

['-', 'P', 'A', '-', '-', 'W', 'H', 'E', 'A', 'E']


gap extension 없을때

In [66]:
sum_score_BLOSUM62 = 0

for i in range(len(rev_seq1_BLOSUM62)):
  
  a = rev_seq1_BLOSUM62[i]
  b = rev_seq2_BLOSUM62[i]

  if a == '-' or b == '-':
 
    #if gap_open_count != 0:
    #  sum_score_BLOSUM62 = sum_score_BLOSUM62 + int(gap_extension_penalty)
    #else:
      sum_score_BLOSUM62 = sum_score_BLOSUM62 + int(gap_opening)
    #  gap_open_count = 1

  else:
    c = matrix_score1(a,b)
    sum_score_BLOSUM62 = int(c) + sum_score_BLOSUM62
    #gap_open_count = 0
    
  print(sum_score_BLOSUM62)

-10
-11
-7
-17
-27
-16
-18
-18
-19
-14


gap extension 있을때

In [67]:
sum_score_BLOSUM62 = 0
gap_open_count = 0

#gap_extension_penalty = '-2'

for i in range(len(rev_seq1_BLOSUM62)):
  
  a = rev_seq1_BLOSUM62[i]
  b = rev_seq2_BLOSUM62[i]

  if a == '-' or b == '-':
 
    if gap_open_count != 0:
      sum_score_BLOSUM62 = sum_score_BLOSUM62 + int(gap_extension_penalty)
    else:
      sum_score_BLOSUM62 = sum_score_BLOSUM62 + int(gap_opening)
      gap_open_count = 1

  else:
    c = matrix_score1(a,b)
    sum_score_BLOSUM62 = int(c) + sum_score_BLOSUM62
    gap_open_count = 0

  print(sum_score_BLOSUM62)

print(sum_score_BLOSUM62)

-10
-11
-7
-17
-27
-16
-18
-18
-19
-14
-14


###PAM250 결과

In [68]:
start_seq1_PAM250 = len(seq1)+1
start_seq2_PAM250 = len(seq2)+1
rev_seq1_PAM250 = []
rev_seq2_PAM250 = []

for i in range(len(seq2)+1,1,-1):
  for j in range(len(seq1)+1,1,-1):
    #print("바깥 i 는 ",i)
    #print("바깥 j 는 ",j)

    if i == start_seq2_PAM250 and j == start_seq1_PAM250:

      #print("안쪽 i 는 ",i)
      #print("안쪽 j 는 ",j)
      #print("start_seq2 는 ",start_seq2)
      #print("start_seq1 은 ",start_seq1)
      
      if direction_matrix2[0][i][j] == 1:
        sc1 = int(score_matrix2[i-1][j-1])
      else:
        sc1 = -1000000
      
      if direction_matrix2[1][i][j] == 1:
        sc2 = int(score_matrix2[i-1][j])
      else:
        sc2 = -1000000
      
      if direction_matrix2[2][i][j] == 1:
        sc3 = int(score_matrix2[i][j-1])
      else:
        sc3 = -1000000

      if str(max(sc1,sc2,sc3)) == str(sc1):
        rev_seq1_PAM250.append(score_matrix2[0][j])
        rev_seq2_PAM250.append(score_matrix2[i][0])
        start_seq1_PAM250 = start_seq1_PAM250 - 1
        start_seq2_PAM250 = start_seq2_PAM250 - 1

      elif str(max(sc1,sc2,sc3)) == str(sc2):
        rev_seq1_PAM250.append('-')
        rev_seq2_PAM250.append(score_matrix2[i][0])
        start_seq2_PAM250 = start_seq2_PAM250 - 1
    
      else:
        rev_seq1_PAM250.append(score_matrix2[0][j])
        rev_seq2_PAM250.append('-')
        start_seq1_PAM250 = start_seq1_PAM250 - 1

      if start_seq2_PAM250==1:
        while start_seq1_PAM250 != 1:
          rev_seq1_PAM250.append(score_matrix2[0][start_seq1_PAM250])
          rev_seq2_PAM250.append('-')
          start_seq1_PAM250 = start_seq1_PAM250 - 1

      elif start_seq1_PAM250==1:
        while start_seq2_PAM250 != 1:
          rev_seq1_PAM250.append('-')
          rev_seq2_PAM250.append(score_matrix2[start_seq2_PAM250][0])
          start_seq2_PAM250 = start_seq2_PAM250 - 1
  

In [69]:
rev_seq1_PAM250.reverse()
rev_seq2_PAM250.reverse()
best_seq1_PAM250 = "".join(rev_seq1_PAM250)
best_seq2_PAM250 = "".join(rev_seq2_PAM250)
print("---Protein Global Alignment---")
print("best seq1 : ",best_seq1_PAM250)
print("best seq2 : ",best_seq2_PAM250)

---Protein Global Alignment---
best seq1 :  HEAGAWGHEE
best seq2 :  --P-AWHEAE


In [70]:
sum_score_PAM250 = 0

for i in range(len(rev_seq1_PAM250)):
  
  a = rev_seq1_PAM250[i]
  b = rev_seq2_PAM250[i]

  if a == '-' or b == '-':
 
    #if gap_open_count != 0:
    #  sum_score_BLOSUM62 = sum_score_BLOSUM62 + int(gap_extension_penalty)
    #else:
      sum_score_PAM250 = sum_score_PAM250 + int(gap_opening)
    #  gap_open_count = 1

  else:
    c = matrix_score2(a,b)
    sum_score_PAM250 = int(c) + sum_score_PAM250
    #gap_open_count = 0
    
  print(sum_score_PAM250)

-10
-20
-19
-29
-27
-10
-12
-11
-11
-7


In [71]:
sum_score_PAM250 = 0
gap_open_count = 0

gap_extension_penalty = '-2'

for i in range(len(rev_seq1_PAM250)):
  
  a = rev_seq1_PAM250[i]
  b = rev_seq2_PAM250[i]

  if a == '-' or b == '-':
 
    if gap_open_count != 0:
      sum_score_PAM250 = sum_score_PAM250 + int(gap_extension_penalty)
    else:
      sum_score_PAM250 = sum_score_PAM250 + int(gap_opening)
      gap_open_count = 1

  else:
    c = matrix_score2(a,b)
    sum_score_PAM250 = int(c) + sum_score_PAM250
    gap_open_count = 0
    
  print(sum_score_PAM250)

print(sum_score_PAM250)

-10
-12
-11
-21
-19
-2
-4
-3
-3
1
1


###PAM30

In [72]:
start_seq1_PAM30 = len(seq1)+1
start_seq2_PAM30 = len(seq2)+1
rev_seq1_PAM30 = []
rev_seq2_PAM30 = []

for i in range(len(seq2)+1,1,-1):
  for j in range(len(seq1)+1,1,-1):
    #print("바깥 i 는 ",i)
    #print("바깥 j 는 ",j)

    if i == start_seq2_PAM30 and j == start_seq1_PAM30:

      #print("안쪽 i 는 ",i)
      #print("안쪽 j 는 ",j)
      #print("start_seq2 는 ",start_seq2)
      #print("start_seq1 은 ",start_seq1)
      
      if direction_matrix3[0][i][j] == 1:
        sc1 = int(score_matrix3[i-1][j-1])
      else:
        sc1 = -1000000
      
      if direction_matrix3[1][i][j] == 1:
        sc2 = int(score_matrix3[i-1][j])
      else:
        sc2 = -1000000
      
      if direction_matrix3[2][i][j] == 1:
        sc3 = int(score_matrix3[i][j-1])
      else:
        sc3 = -1000000

      if str(max(sc1,sc2,sc3)) == str(sc1):
        rev_seq1_PAM30.append(score_matrix3[0][j])
        rev_seq2_PAM30.append(score_matrix3[i][0])
        start_seq1_PAM30 = start_seq1_PAM30 - 1
        start_seq2_PAM30 = start_seq2_PAM30 - 1

      elif str(max(sc1,sc2,sc3)) == str(sc2):
        rev_seq1_PAM30.append('-')
        rev_seq2_PAM30.append(score_matrix3[i][0])
        start_seq2_PAM30 = start_seq2_PAM30 - 1
    
      else:
        rev_seq1_PAM30.append(score_matrix3[0][j])
        rev_seq2_PAM30.append('-')
        start_seq1_PAM30 = start_seq1_PAM30 - 1

      if start_seq2_PAM30==1:
        while start_seq1_PAM30 != 1:
          rev_seq1_PAM30.append(score_matrix3[0][start_seq1_PAM30])
          rev_seq2_PAM30.append('-')
          start_seq1_PAM30 = start_seq1_PAM30 - 1

      elif start_seq1_PAM30==1:
        while start_seq2_PAM30 != 1:
          rev_seq1_PAM30.append('-')
          rev_seq2_PAM30.append(score_matrix3[start_seq2_PAM30][0])
          start_seq2_PAM30 = start_seq2_PAM30 - 1

In [73]:
rev_seq1_PAM30.reverse()
rev_seq2_PAM30.reverse()
best_seq1_PAM30 = "".join(rev_seq1_PAM30)
best_seq2_PAM30 = "".join(rev_seq2_PAM30)
print("---Protein Global Alignment---")
print("best seq1 : ",best_seq1_PAM30)
print("best seq2 : ",best_seq2_PAM30)

---Protein Global Alignment---
best seq1 :  HEAGAWGHE-E
best seq2 :  --P-AW-HEAE


In [74]:
for i in range(len(seq2)+2):
  print(score_matrix3[i])

['0', '0', 'H', 'E', 'A', 'G', 'A', 'W', 'G', 'H', 'E', 'E']
['0', '0', '-10', '-20', '-30', '-40', '-50', '-60', '-70', '-80', '-90', '-100']
['P', '-10', '-4', '-14', '-22', '-32', '-42', '-52', '-62', '-72', '-82', '-92']
['A', '-20', '-14', '-6', '-8', '-18', '-26', '-36', '-46', '-56', '-66', '-76']
['W', '-30', '-24', '-16', '-18', '-23', '-31', '-13', '-23', '-33', '-43', '-53']
['H', '-40', '-21', '-26', '-23', '-27', '-30', '-23', '-22', '-14', '-24', '-34']
['E', '-50', '-31', '-13', '-23', '-27', '-29', '-33', '-27', '-24', '-6', '-16']
['A', '-60', '-41', '-23', '-7', '-17', '-21', '-31', '-35', '-34', '-16', '-8']
['E', '-70', '-51', '-33', '-17', '-11', '-19', '-29', '-35', '-40', '-26', '-8']


In [75]:
print(direction_matrix3)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 0.]
  [0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1.]
  [0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1.]
  [0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
  [0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0.]
  [0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 

In [76]:
sum_score_PAM30 = 0

for i in range(len(rev_seq1_PAM30)):
  
  a = rev_seq1_PAM30[i]
  b = rev_seq2_PAM30[i]

  if a == '-' or b == '-':
 
    #if gap_open_count != 0:
    #  sum_score_BLOSUM62 = sum_score_BLOSUM62 + int(gap_extension_penalty)
    #else:
      sum_score_PAM30 = sum_score_PAM30 + int(gap_opening)
    #  gap_open_count = 1

  else:
    c = matrix_score3(a,b)
    sum_score_PAM30 = int(c) + sum_score_PAM30
    #gap_open_count = 0
    
  print(sum_score_PAM30)

-10
-20
-22
-32
-26
-13
-23
-14
-6
-16
-8


In [77]:
sum_score_PAM30 = 0
gap_open_count = 0

gap_extension_penalty = '-2'

for i in range(len(rev_seq1_PAM30)):
  
  a = rev_seq1_PAM30[i]
  b = rev_seq2_PAM30[i]

  if a == '-' or b == '-':
 
    if gap_open_count != 0:
      sum_score_PAM30 = sum_score_PAM30 + int(gap_extension_penalty)
    else:
      sum_score_PAM30 = sum_score_PAM30 + int(gap_opening)
      gap_open_count = 1

  else:
    c = matrix_score3(a,b)
    sum_score_PAM30 = int(c) + sum_score_PAM30
    gap_open_count = 0
    
  print(sum_score_PAM30)

print(sum_score_PAM30)

-10
-12
-14
-24
-18
-5
-15
-6
2
-8
0
0


###PAM70

In [78]:
start_seq1_PAM70 = len(seq1)+1
start_seq2_PAM70 = len(seq2)+1
rev_seq1_PAM70 = []
rev_seq2_PAM70 = []

for i in range(len(seq2)+1,1,-1):
  for j in range(len(seq1)+1,1,-1):
    #print("바깥 i 는 ",i)
    #print("바깥 j 는 ",j)

    if i == start_seq2_PAM70 and j == start_seq1_PAM70:

      #print("안쪽 i 는 ",i)
      #print("안쪽 j 는 ",j)
      #print("start_seq2 는 ",start_seq2)
      #print("start_seq1 은 ",start_seq1)
      
      if direction_matrix4[0][i][j] == 1:
        sc1 = int(score_matrix4[i-1][j-1])
      else:
        sc1 = -1000000
      
      if direction_matrix4[1][i][j] == 1:
        sc2 = int(score_matrix4[i-1][j])
      else:
        sc2 = -1000000
      
      if direction_matrix4[2][i][j] == 1:
        sc3 = int(score_matrix4[i][j-1])
      else:
        sc3 = -1000000

      if str(max(sc1,sc2,sc3)) == str(sc1):
        rev_seq1_PAM70.append(score_matrix4[0][j])
        rev_seq2_PAM70.append(score_matrix4[i][0])
        start_seq1_PAM70 = start_seq1_PAM70 - 1
        start_seq2_PAM70 = start_seq2_PAM70 - 1

      elif str(max(sc1,sc2,sc3)) == str(sc2):
        rev_seq1_PAM70.append('-')
        rev_seq2_PAM70.append(score_matrix4[i][0])
        start_seq2_PAM70 = start_seq2_PAM70 - 1
    
      else:
        rev_seq1_PAM70.append(score_matrix4[0][j])
        rev_seq2_PAM70.append('-')
        start_seq1_PAM70 = start_seq1_PAM70 - 1

      if start_seq2_PAM70==1:
        while start_seq1_PAM70 != 1:
          rev_seq1_PAM70.append(score_matrix4[0][start_seq1_PAM70])
          rev_seq2_PAM70.append('-')
          start_seq1_PAM70 = start_seq1_PAM70 - 1

      elif start_seq1_PAM70==1:
        while start_seq2_PAM70 != 1:
          rev_seq1_PAM70.append('-')
          rev_seq2_PAM70.append(score_matrix4[start_seq2_PAM70][0])
          start_seq2_PAM70 = start_seq2_PAM70 - 1

In [79]:
rev_seq1_PAM70.reverse()
rev_seq2_PAM70.reverse()
best_seq1_PAM70 = "".join(rev_seq1_PAM70)
best_seq2_PAM70 = "".join(rev_seq2_PAM70)
print("---Protein Global Alignment---")
print("best seq1 : ",best_seq1_PAM70)
print("best seq2 : ",best_seq2_PAM70)

---Protein Global Alignment---
best seq1 :  HEAGAWGHE-E
best seq2 :  --P-AW-HEAE


In [80]:
sum_score_PAM70 = 0

for i in range(len(rev_seq1_PAM70)):
  
  a = rev_seq1_PAM70[i]
  b = rev_seq2_PAM70[i]

  if a == '-' or b == '-':
 
    #if gap_open_count != 0:
    #  sum_score_BLOSUM62 = sum_score_BLOSUM62 + int(gap_extension_penalty)
    #else:
      sum_score_PAM70 = sum_score_PAM70 + int(gap_opening)
    #  gap_open_count = 1

  else:
    c = matrix_score4(a,b)
    sum_score_PAM70 = int(c) + sum_score_PAM70
    #gap_open_count = 0
    
  print(sum_score_PAM70)

-10
-20
-20
-30
-25
-12
-22
-14
-8
-18
-12


In [81]:
sum_score_PAM70 = 0
gap_open_count = 0

gap_extension_penalty = '-2'

for i in range(len(rev_seq1_PAM70)):
  
  a = rev_seq1_PAM70[i]
  b = rev_seq2_PAM70[i]

  if a == '-' or b == '-':
 
    if gap_open_count != 0:
      sum_score_PAM70 = sum_score_PAM70 + int(gap_extension_penalty)
    else:
      sum_score_PAM70 = sum_score_PAM70 + int(gap_opening)
      gap_open_count = 1

  else:
    c = matrix_score4(a,b)
    sum_score_PAM70 = int(c) + sum_score_PAM70
    gap_open_count = 0
    
  print(sum_score_PAM70)

print(sum_score_PAM70)

-10
-12
-12
-22
-17
-4
-14
-6
0
-10
-4
-4


###BLOSUM45

In [82]:
start_seq1_BLOSUM45 = len(seq1)+1
start_seq2_BLOSUM45 = len(seq2)+1
rev_seq1_BLOSUM45 = []
rev_seq2_BLOSUM45 = []

for i in range(len(seq2)+1,1,-1):
  for j in range(len(seq1)+1,1,-1):
    #print("바깥 i 는 ",i)
    #print("바깥 j 는 ",j)

    if i == start_seq2_BLOSUM45 and j == start_seq1_BLOSUM45:

      #print("안쪽 i 는 ",i)
      #print("안쪽 j 는 ",j)
      #print("start_seq2 는 ",start_seq2)
      #print("start_seq1 은 ",start_seq1)
      
      if direction_matrix5[0][i][j] == 1:
        sc1 = int(score_matrix5[i-1][j-1])
      else:
        sc1 = -1000000
      
      if direction_matrix5[1][i][j] == 1:
        sc2 = int(score_matrix5[i-1][j])
      else:
        sc2 = -1000000
      
      if direction_matrix5[2][i][j] == 1:
        sc3 = int(score_matrix5[i][j-1])
      else:
        sc3 = -1000000

      if str(max(sc1,sc2,sc3)) == str(sc1):
        rev_seq1_BLOSUM45.append(score_matrix5[0][j])
        rev_seq2_BLOSUM45.append(score_matrix5[i][0])
        start_seq1_BLOSUM45 = start_seq1_BLOSUM45 - 1
        start_seq2_BLOSUM45 = start_seq2_BLOSUM45 - 1

      elif str(max(sc1,sc2,sc3)) == str(sc2):
        rev_seq1_BLOSUM45.append('-')
        rev_seq2_BLOSUM45.append(score_matrix5[i][0])
        start_seq2_BLOSUM45 = start_seq2_BLOSUM45 - 1
    
      else:
        rev_seq1_BLOSUM45.append(score_matrix5[0][j])
        rev_seq2_BLOSUM45.append('-')
        start_seq1_BLOSUM45 = start_seq1_BLOSUM45 - 1

      if start_seq2_BLOSUM45==1:
        while start_seq1_BLOSUM45 != 1:
          rev_seq1_BLOSUM45.append(score_matrix5[0][start_seq1_BLOSUM45])
          rev_seq2_BLOSUM45.append('-')
          start_seq1_BLOSUM45 = start_seq1_BLOSUM45 - 1

      elif start_seq1_BLOSUM45==1:
        while start_seq2_BLOSUM45 != 1:
          rev_seq1_BLOSUM45.append('-')
          rev_seq2_BLOSUM45.append(score_matrix5[start_seq2_BLOSUM45][0])
          start_seq2_BLOSUM45 = start_seq2_BLOSUM45 - 1

In [83]:
rev_seq1_BLOSUM45.reverse()
rev_seq2_BLOSUM45.reverse()
best_seq1_BLOSUM45 = "".join(rev_seq1_BLOSUM45)
best_seq2_BLOSUM45 = "".join(rev_seq2_BLOSUM45)
print("---Protein Global Alignment---")
print("best seq1 : ",best_seq1_BLOSUM45)
print("best seq2 : ",best_seq2_BLOSUM45)

---Protein Global Alignment---
best seq1 :  HEAGAWGHEE
best seq2 :  -PA--WHEAE


In [84]:
sum_score_BLOSUM45 = 0

for i in range(len(rev_seq1_BLOSUM45)):
  
  a = rev_seq1_BLOSUM45[i]
  b = rev_seq2_BLOSUM45[i]

  if a == '-' or b == '-':
 
    #if gap_open_count != 0:
    #  sum_score_BLOSUM62 = sum_score_BLOSUM62 + int(gap_extension_penalty)
    #else:
      sum_score_BLOSUM45 = sum_score_BLOSUM45 + int(gap_opening)
    #  gap_open_count = 1

  else:
    c = matrix_score5(a,b)
    sum_score_BLOSUM45 = int(c) + sum_score_BLOSUM45
    #gap_open_count = 0
    
  print(sum_score_BLOSUM45)

-10
-10
-5
-15
-25
-10
-12
-12
-13
-7


In [85]:
sum_score_BLOSUM45 = 0
gap_open_count = 0

gap_extension_penalty = '-2'

for i in range(len(rev_seq1_BLOSUM45)):
  
  a = rev_seq1_BLOSUM45[i]
  b = rev_seq2_BLOSUM45[i]

  if a == '-' or b == '-':
 
    if gap_open_count != 0:
      sum_score_BLOSUM45 = sum_score_BLOSUM45 + int(gap_extension_penalty)
    else:
      sum_score_BLOSUM45 = sum_score_BLOSUM45 + int(gap_opening)
      gap_open_count = 1

  else:
    c = matrix_score5(a,b)
    sum_score_BLOSUM45 = int(c) + sum_score_BLOSUM45
    gap_open_count = 0
    
  print(sum_score_BLOSUM45)

print(sum_score_BLOSUM45)

-10
-10
-5
-15
-17
-2
-4
-4
-5
1
1


###BLOSUM50

In [86]:
start_seq1_BLOSUM50 = len(seq1)+1
start_seq2_BLOSUM50 = len(seq2)+1
rev_seq1_BLOSUM50 = []
rev_seq2_BLOSUM50 = []

for i in range(len(seq2)+1,1,-1):
  for j in range(len(seq1)+1,1,-1):
    #print("바깥 i 는 ",i)
    #print("바깥 j 는 ",j)

    if i == start_seq2_BLOSUM50 and j == start_seq1_BLOSUM50:

      #print("안쪽 i 는 ",i)
      #print("안쪽 j 는 ",j)
      #print("start_seq2 는 ",start_seq2)
      #print("start_seq1 은 ",start_seq1)
      
      if direction_matrix6[0][i][j] == 1:
        sc1 = int(score_matrix6[i-1][j-1])
      else:
        sc1 = -1000000
      
      if direction_matrix6[1][i][j] == 1:
        sc2 = int(score_matrix6[i-1][j])
      else:
        sc2 = -1000000
      
      if direction_matrix6[2][i][j] == 1:
        sc3 = int(score_matrix6[i][j-1])
      else:
        sc3 = -1000000

      if str(max(sc1,sc2,sc3)) == str(sc1):
        rev_seq1_BLOSUM50.append(score_matrix6[0][j])
        rev_seq2_BLOSUM50.append(score_matrix6[i][0])
        start_seq1_BLOSUM50 = start_seq1_BLOSUM50 - 1
        start_seq2_BLOSUM50 = start_seq2_BLOSUM50 - 1

      elif str(max(sc1,sc2,sc3)) == str(sc2):
        rev_seq1_BLOSUM50.append('-')
        rev_seq2_BLOSUM50.append(score_matrix6[i][0])
        start_seq2_BLOSUM50 = start_seq2_BLOSUM50 - 1
    
      else:
        rev_seq1_BLOSUM50.append(score_matrix6[0][j])
        rev_seq2_BLOSUM50.append('-')
        start_seq1_BLOSUM50 = start_seq1_BLOSUM50 - 1

      if start_seq2_BLOSUM50==1:
        while start_seq1_BLOSUM50 != 1:
          rev_seq1_BLOSUM50.append(score_matrix6[0][start_seq1_BLOSUM50])
          rev_seq2_BLOSUM50.append('-')
          start_seq1_BLOSUM50 = start_seq1_BLOSUM50 - 1

      elif start_seq1_BLOSUM50==1:
        while start_seq2_BLOSUM50 != 1:
          rev_seq1_BLOSUM50.append('-')
          rev_seq2_BLOSUM50.append(score_matrix6[start_seq2_BLOSUM50][0])
          start_seq2_BLOSUM50 = start_seq2_BLOSUM50 - 1

In [87]:
rev_seq1_BLOSUM50.reverse()
rev_seq2_BLOSUM50.reverse()
best_seq1_BLOSUM50 = "".join(rev_seq1_BLOSUM50)
best_seq2_BLOSUM50 = "".join(rev_seq2_BLOSUM50)
print("---Protein Global Alignment---")
print("best seq1 : ",best_seq1_BLOSUM50)
print("best seq2 : ",best_seq2_BLOSUM50)

---Protein Global Alignment---
best seq1 :  HEAGAWGHEE
best seq2 :  -PA--WHEAE


In [88]:
sum_score_BLOSUM50 = 0

for i in range(len(rev_seq1_BLOSUM50)):
  
  a = rev_seq1_BLOSUM50[i]
  b = rev_seq2_BLOSUM50[i]

  if a == '-' or b == '-':
 
    #if gap_open_count != 0:
    #  sum_score_BLOSUM62 = sum_score_BLOSUM62 + int(gap_extension_penalty)
    #else:
      sum_score_BLOSUM50 = sum_score_BLOSUM50 + int(gap_opening)
    #  gap_open_count = 1

  else:
    c = matrix_score6(a,b)
    sum_score_BLOSUM50 = int(c) + sum_score_BLOSUM50
    #gap_open_count = 0
    
  print(sum_score_BLOSUM50)

-10
-11
-6
-16
-26
-11
-13
-13
-14
-8


In [89]:
sum_score_BLOSUM50 = 0
gap_open_count = 0

gap_extension_penalty = '-2'

for i in range(len(rev_seq1_BLOSUM50)):
  
  a = rev_seq1_BLOSUM50[i]
  b = rev_seq2_BLOSUM50[i]

  if a == '-' or b == '-':
 
    if gap_open_count != 0:
      sum_score_BLOSUM50 = sum_score_BLOSUM50 + int(gap_extension_penalty)
    else:
      sum_score_BLOSUM50 = sum_score_BLOSUM50 + int(gap_opening)
      gap_open_count = 1

  else:
    c = matrix_score6(a,b)
    sum_score_BLOSUM50 = int(c) + sum_score_BLOSUM50
    gap_open_count = 0
    
  print(sum_score_BLOSUM50)

print(sum_score_BLOSUM50)

-10
-11
-6
-16
-18
-3
-5
-5
-6
0
0


###BLOSUM80

In [90]:
start_seq1_BLOSUM80 = len(seq1)+1
start_seq2_BLOSUM80 = len(seq2)+1
rev_seq1_BLOSUM80 = []
rev_seq2_BLOSUM80 = []

for i in range(len(seq2)+1,1,-1):
  for j in range(len(seq1)+1,1,-1):
    #print("바깥 i 는 ",i)
    #print("바깥 j 는 ",j)

    if i == start_seq2_BLOSUM80 and j == start_seq1_BLOSUM80:

      #print("안쪽 i 는 ",i)
      #print("안쪽 j 는 ",j)
      #print("start_seq2 는 ",start_seq2)
      #print("start_seq1 은 ",start_seq1)
      
      if direction_matrix7[0][i][j] == 1:
        sc1 = int(score_matrix7[i-1][j-1])
      else:
        sc1 = -1000000
      
      if direction_matrix7[1][i][j] == 1:
        sc2 = int(score_matrix7[i-1][j])
      else:
        sc2 = -1000000
      
      if direction_matrix7[2][i][j] == 1:
        sc3 = int(score_matrix7[i][j-1])
      else:
        sc3 = -1000000

      if str(max(sc1,sc2,sc3)) == str(sc1):
        rev_seq1_BLOSUM80.append(score_matrix7[0][j])
        rev_seq2_BLOSUM80.append(score_matrix7[i][0])
        start_seq1_BLOSUM80 = start_seq1_BLOSUM80 - 1
        start_seq2_BLOSUM80 = start_seq2_BLOSUM80 - 1

      elif str(max(sc1,sc2,sc3)) == str(sc2):
        rev_seq1_BLOSUM80.append('-')
        rev_seq2_BLOSUM80.append(score_matrix7[i][0])
        start_seq2_BLOSUM80 = start_seq2_BLOSUM80 - 1
    
      else:
        rev_seq1_BLOSUM80.append(score_matrix7[0][j])
        rev_seq2_BLOSUM80.append('-')
        start_seq1_BLOSUM80 = start_seq1_BLOSUM80 - 1

      if start_seq2_BLOSUM80==1:
        while start_seq1_BLOSUM80 != 1:
          rev_seq1_BLOSUM80.append(score_matrix7[0][start_seq1_BLOSUM80])
          rev_seq2_BLOSUM80.append('-')
          start_seq1_BLOSUM80 = start_seq1_BLOSUM80 - 1

      elif start_seq1_BLOSUM80==1:
        while start_seq2_BLOSUM80 != 1:
          rev_seq1_BLOSUM80.append('-')
          rev_seq2_BLOSUM80.append(score_matrix7[start_seq2_BLOSUM80][0])
          start_seq2_BLOSUM80 = start_seq2_BLOSUM80 - 1

In [91]:
rev_seq1_BLOSUM80.reverse()
rev_seq2_BLOSUM80.reverse()
best_seq1_BLOSUM80 = "".join(rev_seq1_BLOSUM80)
best_seq2_BLOSUM80 = "".join(rev_seq2_BLOSUM80)
print("---Protein Global Alignment---")
print("best seq1 : ",best_seq1_BLOSUM80)
print("best seq2 : ",best_seq2_BLOSUM80)

---Protein Global Alignment---
best seq1 :  HEAGAWGHEE
best seq2 :  --P-AWHEAE


In [92]:
sum_score_BLOSUM80 = 0

for i in range(len(rev_seq1_BLOSUM80)):
  
  a = rev_seq1_BLOSUM80[i]
  b = rev_seq2_BLOSUM80[i]

  if a == '-' or b == '-':
 
    #if gap_open_count != 0:
    #  sum_score_BLOSUM62 = sum_score_BLOSUM62 + int(gap_extension_penalty)
    #else:
      sum_score_BLOSUM80 = sum_score_BLOSUM80 + int(gap_opening)
    #  gap_open_count = 1

  else:
    c = matrix_score7(a,b)
    sum_score_BLOSUM80 = int(c) + sum_score_BLOSUM80
    #gap_open_count = 0
    
  print(sum_score_BLOSUM80)

-10
-20
-21
-31
-26
-15
-18
-18
-19
-13


In [93]:
sum_score_BLOSUM80 = 0
gap_open_count = 0

gap_extension_penalty = '-2'

for i in range(len(rev_seq1_BLOSUM80)):
  
  a = rev_seq1_BLOSUM80[i]
  b = rev_seq2_BLOSUM80[i]

  if a == '-' or b == '-':
 
    if gap_open_count != 0:
      sum_score_BLOSUM80 = sum_score_BLOSUM80 + int(gap_extension_penalty)
    else:
      sum_score_BLOSUM80 = sum_score_BLOSUM80 + int(gap_opening)
      gap_open_count = 1

  else:
    c = matrix_score7(a,b)
    sum_score_BLOSUM80 = int(c) + sum_score_BLOSUM80
    gap_open_count = 0
    
  print(sum_score_BLOSUM80)

print(sum_score_BLOSUM80)

-10
-12
-13
-23
-18
-7
-10
-10
-11
-5
-5


###BLOSUM90

In [94]:
start_seq1_BLOSUM90 = len(seq1)+1
start_seq2_BLOSUM90 = len(seq2)+1
rev_seq1_BLOSUM90 = []
rev_seq2_BLOSUM90 = []

for i in range(len(seq2)+1,1,-1):
  for j in range(len(seq1)+1,1,-1):
    #print("바깥 i 는 ",i)
    #print("바깥 j 는 ",j)

    if i == start_seq2_BLOSUM90 and j == start_seq1_BLOSUM90:

      #print("안쪽 i 는 ",i)
      #print("안쪽 j 는 ",j)
      #print("start_seq2 는 ",start_seq2)
      #print("start_seq1 은 ",start_seq1)
      
      if direction_matrix8[0][i][j] == 1:
        sc1 = int(score_matrix8[i-1][j-1])
      else:
        sc1 = -1000000
      
      if direction_matrix8[1][i][j] == 1:
        sc2 = int(score_matrix8[i-1][j])
      else:
        sc2 = -1000000
      
      if direction_matrix8[2][i][j] == 1:
        sc3 = int(score_matrix8[i][j-1])
      else:
        sc3 = -1000000

      if str(max(sc1,sc2,sc3)) == str(sc1):
        rev_seq1_BLOSUM90.append(score_matrix8[0][j])
        rev_seq2_BLOSUM90.append(score_matrix8[i][0])
        start_seq1_BLOSUM90 = start_seq1_BLOSUM90 - 1
        start_seq2_BLOSUM90 = start_seq2_BLOSUM90 - 1

      elif str(max(sc1,sc2,sc3)) == str(sc2):
        rev_seq1_BLOSUM90.append('-')
        rev_seq2_BLOSUM90.append(score_matrix8[i][0])
        start_seq2_BLOSUM90 = start_seq2_BLOSUM90 - 1
    
      else:
        rev_seq1_BLOSUM90.append(score_matrix8[0][j])
        rev_seq2_BLOSUM90.append('-')
        start_seq1_BLOSUM90 = start_seq1_BLOSUM90 - 1

      if start_seq2_BLOSUM90==1:
        while start_seq1_BLOSUM90 != 1:
          rev_seq1_BLOSUM90.append(score_matrix8[0][start_seq1_BLOSUM90])
          rev_seq2_BLOSUM90.append('-')
          start_seq1_BLOSUM90 = start_seq1_BLOSUM90 - 1

      elif start_seq1_BLOSUM90==1:
        while start_seq2_BLOSUM90 != 1:
          rev_seq1_BLOSUM90.append('-')
          rev_seq2_BLOSUM90.append(score_matrix8[start_seq2_BLOSUM90][0])
          start_seq2_BLOSUM90 = start_seq2_BLOSUM90 - 1

In [95]:
rev_seq1_BLOSUM90.reverse()
rev_seq2_BLOSUM90.reverse()
best_seq1_BLOSUM90 = "".join(rev_seq1_BLOSUM90)
best_seq2_BLOSUM90 = "".join(rev_seq2_BLOSUM90)
print("---Protein Global Alignment---")
print("best seq1 : ",best_seq1_BLOSUM90)
print("best seq2 : ",best_seq2_BLOSUM90)

---Protein Global Alignment---
best seq1 :  HEAGAWGHEE
best seq2 :  --P-AWHEAE


In [96]:
sum_score_BLOSUM90 = 0

for i in range(len(rev_seq1_BLOSUM90)):
  
  a = rev_seq1_BLOSUM90[i]
  b = rev_seq2_BLOSUM90[i]

  if a == '-' or b == '-':
 
    #if gap_open_count != 0:
    #  sum_score_BLOSUM62 = sum_score_BLOSUM62 + int(gap_extension_penalty)
    #else:
      sum_score_BLOSUM90 = sum_score_BLOSUM90 + int(gap_opening)
    #  gap_open_count = 1

  else:
    c = matrix_score8(a,b)
    sum_score_BLOSUM90 = int(c) + sum_score_BLOSUM90
    #gap_open_count = 0
    
  print(sum_score_BLOSUM90)

-10
-20
-21
-31
-26
-15
-18
-19
-20
-14


In [97]:
sum_score_BLOSUM90 = 0
gap_open_count = 0

gap_extension_penalty = '-2'

for i in range(len(rev_seq1_BLOSUM90)):
  
  a = rev_seq1_BLOSUM90[i]
  b = rev_seq2_BLOSUM90[i]

  if a == '-' or b == '-':
 
    if gap_open_count != 0:
      sum_score_BLOSUM90 = sum_score_BLOSUM90 + int(gap_extension_penalty)
    else:
      sum_score_BLOSUM90 = sum_score_BLOSUM90 + int(gap_opening)
      gap_open_count = 1

  else:
    c = matrix_score8(a,b)
    sum_score_BLOSUM90 = int(c) + sum_score_BLOSUM90
    gap_open_count = 0
    
  print(sum_score_BLOSUM90)

print(sum_score_BLOSUM90)

-10
-12
-13
-23
-18
-7
-10
-11
-12
-6
-6


====================================================================

#**결과 출력**

In [99]:
score_arr = [sum_score_BLOSUM62,
  sum_score_PAM250,
  sum_score_PAM30,
  sum_score_PAM70,
  sum_score_BLOSUM45,
  sum_score_BLOSUM50,
  sum_score_BLOSUM80,
  sum_score_BLOSUM90]

In [100]:
print(score_arr)

[-14, 1, 0, -4, 1, 0, -5, -6]
