In [ ]:
seq1 = input("first seq : ") # seq 1 입력
lseq1 = list(seq1)
seq2 = input("second seq : ") # seq 2 입력
lseq2 = list(seq2)
gap_score = input("gap score : ") # gap score 입력
match_score = input("match score : ") # match score 입력
mismatch_score = input("mismatch score : ") # mismatch score 입력

first seq : ACTGATTCA
second seq : ACGCATCA
gap score : -2
match score : 2
mismatch score : -3


In [ ]:
score_matrix = [['0'] * (len(seq1)+2) for _ in range(len(seq2)+2) ]
#print(score_matrix)

#for i in range(len(seq2)+2):
#  print(score_matrix[i])

for i in range(2,len(seq1)+2,1):
  #print(i)
  score_matrix[0][i] = lseq1[i-2]
  #print(score_matrix[0][i])

for i in range(2,len(lseq2)+2,1):
  score_matrix[i][0] = lseq2[i-2]

In [ ]:
for i in range(1,len(seq1)+2,1):
  if i == 1:
    score_matrix[1][i] = '0'
  else:
    a = int(score_matrix[1][i-1]) + int(gap_score)
    score_matrix[1][i] = str(a)

for i in range(1,len(seq2)+2,1):
  if i == 1:
    score_matrix[i][1] = '0'
  else:
    a = int(score_matrix[i-1][1]) + int(gap_score)
    score_matrix[i][1] = str(a)

In [ ]:
import numpy as np

In [ ]:
direction_matrix = np.zeros((3,len(seq2)+2,len(seq1)+2))

In [ ]:
for i in range(2,len(seq2)+2,1):
  for j in range(2,len(seq1)+2,1):
    if score_matrix[i][0] == score_matrix[0][j]:
      s = match_score
    else:
      s = mismatch_score
    
    s1 = int(score_matrix[i-1][j-1]) + int(s)
    s2 = int(score_matrix[i-1][j]) + int(gap_score)
    s3 = int(score_matrix[i][j-1]) + int(gap_score)
    
    score_matrix[i][j] = str(max(s1,s2,s3))

    if str(max(s1,s2,s3)) == str(s1):
      #대각선 방향
      direction_matrix[0][i][j] = 1
    if str(max(s1,s2,s3)) == str(s2):
      direction_matrix[1][i][j] = 1
    if str(max(s1,s2,s3)) == str(s3):
      direction_matrix[2][i][j] = 1

In [ ]:
for i in range(len(seq2)+2):
  print(score_matrix[i])

['0', '0', 'A', 'C', 'T', 'G', 'A', 'T', 'T', 'C', 'A']
['0', '0', '-2', '-4', '-6', '-8', '-10', '-12', '-14', '-16', '-18']
['A', '-2', '2', '0', '-2', '-4', '-6', '-8', '-10', '-12', '-14']
['C', '-4', '0', '4', '2', '0', '-2', '-4', '-6', '-8', '-10']
['G', '-6', '-2', '2', '1', '4', '2', '0', '-2', '-4', '-6']
['C', '-8', '-4', '0', '-1', '2', '1', '-1', '-3', '0', '-2']
['A', '-10', '-6', '-2', '-3', '0', '4', '2', '0', '-2', '2']
['T', '-12', '-8', '-4', '0', '-2', '2', '6', '4', '2', '0']
['C', '-14', '-10', '-6', '-2', '-3', '0', '4', '3', '6', '4']
['A', '-16', '-12', '-8', '-4', '-5', '-1', '2', '1', '4', '8']


In [ ]:
print(direction_matrix)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0.]
  [0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0.]
  [0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0.]
  [0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0.]
  [0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1.]
  [0. 0. 1. 1. 1. 0. 1. 1. 0. 0. 0.]
  [0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0

In [ ]:
start_seq1 = len(seq1)+1
start_seq2 = len(seq2)+1
rev_seq1 = []
rev_seq2 = []

for i in range(len(seq2)+1,1,-1):
  for j in range(len(seq1)+1,1,-1):
    print(i)
    print(j)

    if i == start_seq2 and j == start_seq1:
      print(start_seq2)
      print(start_seq1)

      if direction_matrix[0][i][j] == 1:
        sc1 = int(score_matrix[i-1][j-1])
      else:
        sc1 = -1000000
      
      if direction_matrix[1][i][j] == 1:
        sc2 = int(score_matrix[i-1][j])
      else:
        sc2 = -1000000
      
      if direction_matrix[2][i][j] == 1:
        sc3 = int(score_matrix[i][j-1])
      else:
        sc3 = -1000000

      if str(max(sc1,sc2,sc3)) == str(sc1):
        rev_seq1.append(score_matrix[0][j])
        rev_seq2.append(score_matrix[i][0])
        start_seq1 = start_seq1 - 1
        start_seq2 = start_seq2 - 1

      elif str(max(sc1,sc2,sc3)) == str(sc2):
        rev_seq1.append('-')
        rev_seq2.append(score_matrix[i][0])
        start_seq2 = start_seq2 - 1
    
      else:
        rev_seq1.append(score_matrix[0][j])
        rev_seq2.append('-')
        start_seq1 = start_seq1 - 1
      
      if start_seq2==1 and start_seq1==2:
        rev_seq1.append(score_matrix[0][start_seq1])
        rev_seq2.append('-')
        break

      elif start_seq2==2 and start_seq1==1:
        rev_seq1.append('-')
        rev_seq2.append(score_matrix[start_seq2][0])
        break
      
      print(rev_seq1)
      print(rev_seq2)

9
10
9
10
['A']
['A']
9
9
9
8
9
7
9
6
9
5
9
4
9
3
9
2
8
10
8
9
8
9
['A', 'C']
['A', 'C']
8
8
8
7
8
6
8
5
8
4
8
3
8
2
7
10
7
9
7
8
7
8
['A', 'C', 'T']
['A', 'C', '-']
7
7
7
7
['A', 'C', 'T', 'T']
['A', 'C', '-', 'T']
7
6
7
5
7
4
7
3
7
2
6
10
6
9
6
8
6
7
6
6
6
6
['A', 'C', 'T', 'T', 'A']
['A', 'C', '-', 'T', 'A']
6
5
6
4
6
3
6
2
5
10
5
9
5
8
5
7
5
6
5
5
5
5
['A', 'C', 'T', 'T', 'A', '-']
['A', 'C', '-', 'T', 'A', 'C']
5
4
5
3
5
2
4
10
4
9
4
8
4
7
4
6
4
5
4
5
['A', 'C', 'T', 'T', 'A', '-', 'G']
['A', 'C', '-', 'T', 'A', 'C', 'G']
4
4
4
3
4
2
3
10
3
9
3
8
3
7
3
6
3
5
3
4
3
4
['A', 'C', 'T', 'T', 'A', '-', 'G', 'T']
['A', 'C', '-', 'T', 'A', 'C', 'G', '-']
3
3
3
3
['A', 'C', 'T', 'T', 'A', '-', 'G', 'T', 'C']
['A', 'C', '-', 'T', 'A', 'C', 'G', '-', 'C']
3
2
2
10
2
9
2
8
2
7
2
6
2
5
2
4
2
3
2
2
2
2
['A', 'C', 'T', 'T', 'A', '-', 'G', 'T', 'C', 'A']
['A', 'C', '-', 'T', 'A', 'C', 'G', '-', 'C', 'A']


In [ ]:
print(rev_seq1)
print(rev_seq2)

['A', 'C', 'T', 'T', 'A', '-', 'G', 'T', 'C', 'A']
['A', 'C', '-', 'T', 'A', 'C', 'G', '-', 'C', 'A']


In [ ]:
rev_seq1.reverse()
rev_seq2.reverse()
print(rev_seq1)
print(rev_seq2)

['A', 'C', 'T', 'G', '-', 'A', 'T', 'T', 'C', 'A']
['A', 'C', '-', 'G', 'C', 'A', 'T', '-', 'C', 'A']


In [ ]:
best_seq1 = "".join(rev_seq1)
best_seq2 = "".join(rev_seq2)

In [ ]:
print("---DNA Global Alignment---")
print("best seq1 : ",best_seq1)
print("best seq2 : ",best_seq2)

---DNA Global Alignment---
best seq1 :  ACTG-ATTCA
best seq2 :  AC-GCAT-CA
